[package]
edition="2021"
name   ="json-gen-actix"
version="0.1.0"

[dependencies]
actix-web  ={ version="4.9.0", features=["compress-gzip"] }
fake       ={ version="3.1.0", features=["derive"] }
num_cpus   ="1.16.0"
parking_lot="0.12.3"
rand       ="0.8.5"
rand_chacha="0.3.1"
rayon      ="1.10.0"
serde      ={ version="1.0.217", features=["derive"] }
